# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://mohitjuneja.github.io/numerical_linear_algebra/"

git_url = "https://github.com/mohitjuneja/numerical-linear-algebra-v2/tree/master/"

def custom_doc_links(name): return None
