# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'HelloSayer']

# Cell
def say_hello(to):
    "This function say_hello says hello to somebody"
#     print(f"Hello {to}!")
    return f"Hello {to}!"

# Cell
class HelloSayer:
    "Some initial documentation `to` using `say_hello` for the class"
    def __init__(self, to): self.to = to
    def say(self):
        "Do the saying"
        return say_hello(self.to)